# Generated by Django 4.0.4 on 2022-05-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_trainer_trainer'),
        ('trainers', '0004_alter_workouts_programs'),
        ('Users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.trainer')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainers.workouts')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
