# Generated by Django 4.0.4 on 2022-05-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_subscription_delete_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
