# Generated by Django 4.0.4 on 2022-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
