# Generated by Django 4.0.4 on 2022-05-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='health_condition',
        ),
    ]
