# Generated by Django 4.0.4 on 2022-04-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs', models.CharField(max_length=250)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
